### ISSUE TITLE
irreducible instead of subtype?

### ISSUE THREAD

**Issue by gcanti** [buildo/avenger#79]
https://github.com/buildo/avenger/blob/master/src/types.js#L47

could be written with the `irreducible` function:

```js
const TcombType = t.irreducible('TcombType', isType);
```

**Comment by gcanti** [comment]
Also `t.Str`, `t.Num`, ... are deprecated, use `t.String`, `t.Number` instead. I'll send a PR if you agree.

**Comment by giogonzo** [comment]
Greatly appreciated!

Was also considering switching to the [babel plugin](https://github.com/gcanti/babel-plugin-tcomb) instead of manually applying type checks e.g. here: https://github.com/buildo/avenger/blob/master/src/run.js#L20
Do you see any issue considering the "named parameters" approach I'm following pretty much everywhere?

**Comment by gcanti** [comment]
> Do you see any issue considering the "named parameters" approach I'm following pretty much everywhere?

Not really. Indeed it should be neater:

```js
export function runLocal(params: RunLocalParams) {

...
```

**Comment by giogonzo** [comment]
Thanks! I'll give it a shot soon
